from __future__ import annotations

"""Conventional crystallographic point-group registry.

The registry provides exact direct-coordinate symmetry matrices for all 32
crystallographic point groups in standard conventional settings.

Important
---------
The matrices act on crystallographic direct coordinates, not on an assumed
orthonormal Cartesian basis. ProjectState validation independently checks

    G.T @ M @ G == M

against the user's actual lattice metric. Therefore an incompatible cell/point
group combination fails loudly instead of being silently coerced.

Trigonal groups use hexagonal axes in the built-in registry. Rhombohedral-axis
users can supply explicit symmetry matrices through project JSON.
"""

import re
from dataclasses import dataclass

import numpy as np
import sympy as sp

MatrixKey = tuple[sp.Expr, ...]


def _key(matrix: sp.Matrix) -> MatrixKey:
    return tuple(sp.simplify(value) for value in list(sp.Matrix(matrix)))


def _sort_key(matrix: sp.Matrix) -> tuple[str, ...]:
    return tuple(str(sp.simplify(value)) for value in list(matrix))


def _closure(generators: tuple[sp.Matrix, ...]) -> tuple[sp.Matrix, ...]:
    """Exact finite matrix group generated by `generators`."""
    identity = sp.eye(3)
    found: dict[MatrixKey, sp.Matrix] = {_key(identity): identity}
    generators = tuple(sp.Matrix(generator) for generator in generators)

    changed = True
    while changed:
        changed = False
        current = tuple(found.values())
        for left in current:
            for right in (*generators, *current):
                product = sp.simplify(left * right)
                key = _key(product)
                if key not in found:
                    found[key] = product
                    changed = True
                    if len(found) > 48:
                        raise AssertionError(
                            "Crystallographic point group unexpectedly exceeded order 48."
                        )

    matrices = sorted(found.values(), key=_sort_key)
    matrices.remove(identity)
    return (identity, *matrices)


I = sp.eye(3)
INV = -I

C2_X = sp.diag(1, -1, -1)
C2_Y = sp.diag(-1, 1, -1)
C2_Z = sp.diag(-1, -1, 1)

M_X = sp.diag(-1, 1, 1)
M_Y = sp.diag(1, -1, 1)
M_Z = sp.diag(1, 1, -1)

R4_Z = sp.Matrix(
    [
        [0, -1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ]
)

# Hexagonal direct basis: a1, a2 at gamma=120 degrees, c vertical.
R6_Z_HEX = sp.Matrix(
    [
        [1, -1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ]
)
R3_Z_HEX = sp.simplify(R6_Z_HEX**2)

# Vertical mirror containing a1 and c.
M_A1_HEX = sp.Matrix(
    [
        [1, -1, 0],
        [0, -1, 0],
        [0, 0, 1],
    ]
)

# Two-fold rotation about a1.
C2_A1_HEX = sp.Matrix(
    [
        [1, -1, 0],
        [0, -1, 0],
        [0, 0, -1],
    ]
)

# Cubic cyclic 3-fold about [111].
C3_111 = sp.Matrix(
    [
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
    ]
)

M_XY_SWAP = sp.Matrix(
    [
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ]
)


@dataclass(frozen=True)
class PointGroupDefinition:
    symbol: str
    crystal_family: str
    conventional_setting: str
    expected_order: int
    generators: tuple[sp.Matrix, ...]
    aliases: tuple[str, ...] = ()

    def operations(self) -> tuple[sp.Matrix, ...]:
        operations = _closure(self.generators)
        if len(operations) != self.expected_order:
            raise AssertionError(
                f"{self.symbol}: expected order {self.expected_order}, "
                f"generated {len(operations)}."
            )
        return operations


_DEFINITIONS = (
    PointGroupDefinition("1", "triclinic", "conventional", 1, ()),
    PointGroupDefinition("-1", "triclinic", "conventional", 2, (INV,), ("bar1", "ci")),
    PointGroupDefinition("2", "monoclinic", "unique b", 2, (C2_Y,), ("c2",)),
    PointGroupDefinition("m", "monoclinic", "unique b", 2, (M_Y,), ("cs",)),
    PointGroupDefinition(
        "2/m",
        "monoclinic",
        "unique b",
        4,
        (C2_Y, INV),
        ("2m", "c2h"),
    ),
    PointGroupDefinition(
        "222", "orthorhombic", "conventional", 4, (C2_X, C2_Y), ("d2",)
    ),
    PointGroupDefinition("mm2", "orthorhombic", "2 || c", 4, (M_X, M_Y), ("c2v",)),
    PointGroupDefinition(
        "mmm", "orthorhombic", "conventional", 8, (M_X, M_Y, M_Z), ("d2h",)
    ),
    PointGroupDefinition("4", "tetragonal", "4 || c", 4, (R4_Z,), ("c4",)),
    PointGroupDefinition("-4", "tetragonal", "-4 || c", 4, (-R4_Z,), ("bar4", "s4")),
    PointGroupDefinition("4/m", "tetragonal", "4 || c", 8, (R4_Z, M_Z), ("c4h",)),
    PointGroupDefinition("422", "tetragonal", "4 || c", 8, (R4_Z, C2_X), ("d4",)),
    PointGroupDefinition("4mm", "tetragonal", "4 || c", 8, (R4_Z, M_Y), ("c4v",)),
    PointGroupDefinition(
        "-42m", "tetragonal", "-4 || c", 8, (-R4_Z, C2_X), ("bar42m", "d2d")
    ),
    PointGroupDefinition(
        "4/mmm", "tetragonal", "4 || c", 16, (R4_Z, C2_X, INV), ("d4h",)
    ),
    PointGroupDefinition(
        "3", "trigonal", "hexagonal axes, 3 || c", 3, (R3_Z_HEX,), ("c3",)
    ),
    PointGroupDefinition(
        "-3", "trigonal", "hexagonal axes, -3 || c", 6, (R3_Z_HEX, INV), ("bar3", "c3i")
    ),
    PointGroupDefinition(
        "32", "trigonal", "hexagonal axes, 3 || c", 6, (R3_Z_HEX, C2_A1_HEX), ("d3",)
    ),
    PointGroupDefinition(
        "3m", "trigonal", "hexagonal axes, 3 || c", 6, (R3_Z_HEX, M_A1_HEX), ("c3v",)
    ),
    PointGroupDefinition(
        "-3m",
        "trigonal",
        "hexagonal axes, -3 || c",
        12,
        (R3_Z_HEX, C2_A1_HEX, INV),
        ("bar3m", "d3d"),
    ),
    PointGroupDefinition("6", "hexagonal", "6 || c", 6, (R6_Z_HEX,), ("c6",)),
    PointGroupDefinition(
        "-6", "hexagonal", "-6 || c", 6, (-R6_Z_HEX,), ("bar6", "c3h")
    ),
    PointGroupDefinition("6/m", "hexagonal", "6 || c", 12, (R6_Z_HEX, M_Z), ("c6h",)),
    PointGroupDefinition(
        "622", "hexagonal", "6 || c", 12, (R6_Z_HEX, C2_A1_HEX), ("d6",)
    ),
    PointGroupDefinition(
        "6mm", "hexagonal", "6 || c", 12, (R6_Z_HEX, M_A1_HEX), ("c6v",)
    ),
    PointGroupDefinition(
        "-6m2",
        "hexagonal",
        "-6 || c",
        12,
        (R3_Z_HEX, C2_A1_HEX, M_Z),
        ("bar6m2", "d3h"),
    ),
    PointGroupDefinition(
        "6/mmm", "hexagonal", "6 || c", 24, (R6_Z_HEX, C2_A1_HEX, INV), ("d6h",)
    ),
    PointGroupDefinition(
        "23", "cubic", "conventional cubic axes", 12, (C3_111, C2_X), ("t",)
    ),
    PointGroupDefinition(
        "m-3", "cubic", "conventional cubic axes", 24, (C3_111, C2_X, INV), ("m3", "th")
    ),
    PointGroupDefinition(
        "432", "cubic", "conventional cubic axes", 24, (R4_Z, C3_111), ("o",)
    ),
    PointGroupDefinition(
        "-43m",
        "cubic",
        "conventional cubic axes",
        24,
        (C3_111, C2_X, M_XY_SWAP),
        ("bar43m", "td"),
    ),
    PointGroupDefinition(
        "m-3m",
        "cubic",
        "conventional cubic axes",
        48,
        (R4_Z, C3_111, INV),
        ("m3m", "oh"),
    ),
)


def _normalize_symbol(symbol: str) -> str:
    text = symbol.strip().lower()
    text = text.replace("−", "-").replace("–", "-").replace("—", "-")
    text = text.replace(" ", "").replace("_", "")
    text = re.sub(r"[()]", "", text)
    return text


_BY_CANONICAL = {definition.symbol: definition for definition in _DEFINITIONS}
_BY_ALIAS: dict[str, PointGroupDefinition] = {}

for definition in _DEFINITIONS:
    candidates = (definition.symbol, *definition.aliases)
    for candidate in candidates:
        normalized = _normalize_symbol(candidate)
        existing = _BY_ALIAS.get(normalized)
        if existing is not None and existing.symbol != definition.symbol:
            raise AssertionError(
                f"Ambiguous point-group alias {candidate!r}: "
                f"{existing.symbol} vs {definition.symbol}."
            )
        _BY_ALIAS[normalized] = definition


def point_group_definitions() -> tuple[PointGroupDefinition, ...]:
    return _DEFINITIONS


def resolve_point_group(symbol: str) -> PointGroupDefinition:
    normalized = _normalize_symbol(symbol)
    definition = _BY_ALIAS.get(normalized)
    if definition is None:
        available = ", ".join(item.symbol for item in _DEFINITIONS)
        raise ValueError(
            f"Unknown crystallographic point group {symbol!r}. "
            f"Supported conventional groups: {available}. "
            "For a nonstandard setting, provide explicit symmetry matrices."
        )
    return definition


def point_group_operations(symbol: str) -> tuple[sp.Matrix, ...]:
    return resolve_point_group(symbol).operations()


def point_group_table() -> tuple[dict[str, object], ...]:
    rows = []
    for definition in _DEFINITIONS:
        rows.append(
            {
                "symbol": definition.symbol,
                "crystal_family": definition.crystal_family,
                "conventional_setting": definition.conventional_setting,
                "order": definition.expected_order,
                "aliases": list(definition.aliases),
            }
        )
    return tuple(rows)


def metric_preservation_residual(
    operations: tuple[sp.Matrix, ...],
    metric: np.ndarray,
) -> float:
    M = np.asarray(metric, dtype=float).reshape(3, 3)
    scale = max(float(np.linalg.norm(M)), 1.0)
    worst = 0.0
    for operation in operations:
        G = np.asarray(operation, dtype=float)
        residual = float(np.linalg.norm(G.T @ M @ G - M) / scale)
        worst = max(worst, residual)
    return worst
