from __future__ import annotations

"""Independent classical single-shear PTMC adapter.

This module implements the phenomenological theory of martensite crystallography
(PTMC) as an independent theory branch.  It intentionally does not import
Cayron CT/CMC/SMC or the Ball--James adapter.

Conventions
-----------
* The crystallographic correspondence maps parent direct coordinates to product
  direct coordinates: ``u_M = C @ u_A``.
* Transformation stretches are represented in the symmetric metric-orthonormal
  parent frame ``B_A = M_A^(1/2)``.
* A martensite variant generated by a parent symmetry ``g`` uses
  ``C_i = C @ g^{-1}``.
* A twinned laminate uses
  ``F_pre(f) = U_base + f a⊗n`` where
  ``R_hat U_other - U_base = a⊗n``.
* A slip lattice-invariant shear specified in the product lattice uses
  ``F_pre(gamma) = (I + gamma s⊗q) U`` with ``s·q = 0`` in the
  deformed product frame.
* Habit compatibility is solved as
  ``R F_pre - delta I = b⊗m``.
  ``delta=1`` is a true invariant-plane strain; ``delta != 1`` is the
  Bowles--Mackenzie uniformly dilated-plane extension.
* OR matrices are reported both in the symmetric metric frames and in the
  repository's PTCLab-style conventional Cartesian frames.

The numerical engine returns every discrete admissible root and explicitly
reports the degenerate continuum case instead of sampling it and pretending the
sample is exhaustive.
"""

from collections.abc import Iterable
from dataclasses import asdict, dataclass
from enum import Enum
from typing import Any

import numpy as np
from scipy.optimize import minimize_scalar

from .correspondence import Correspondence
from .lattice import Lattice
from .numerics import DEFAULT_NUMERICAL_POLICY, NumericalPolicy
from .point_groups import point_group_operations

Array = np.ndarray


class LISType(str, Enum):
    """Classical single-shear lattice-invariant deformation mechanism."""

    TWIN = "twin"
    SLIP = "slip"


@dataclass(frozen=True)
class PTMCVariant:
    """One distinct transformation-stretch variant."""

    index: int
    U: Array
    correspondence_M_from_A: Array
    representative_parent_symmetry_index: int
    generating_parent_symmetry_indices: tuple[int, ...]
    polar_rotation_product_from_parent: Array
    principal_stretches: Array
    determinant: float
    maximum_audit_residual: float


@dataclass(frozen=True)
class PTMCTwinRelation:
    """One exact M/M rank-one relation used as a twinning LIS branch.

    Equation:
        R_hat U_other - U_base = a ⊗ n_reference.
    """

    base_variant_index: int
    other_variant_index: int
    branch: int
    rotation_hat: Array
    a: Array
    n_reference: Array
    deformed_twin_plane_normal_base: Array
    twin_plane_product_crystal_base: Array
    twin_shear_magnitude: float
    rank_one_residual: float
    rotation_residual: float


@dataclass(frozen=True)
class PTMCParameterRoots:
    """Auditable roots of the classical single-shear compatibility polynomial."""

    parameter_name: str
    discrete_roots: tuple[float, ...]
    continuum: bool
    domain: tuple[float, float] | None
    polynomial_coefficients_ascending: tuple[float, float, float]
    polynomial_verification_residual: float
    nearest_parameter: float | None
    nearest_middle_stretch_residual: float | None


@dataclass(frozen=True)
class PTMCInvariantLine:
    """Invariant/scaled-invariant line generated by two plane normals."""

    parent_cartesian: Array
    parent_crystal: Array
    product_crystal_base: Array
    deformation_residual: float


@dataclass(frozen=True)
class PTMCHabitSolution:
    """One complete classical PTMC solution branch."""

    lis_type: str
    base_variant_index: int
    other_variant_index: int | None
    twin_branch: int | None
    parameter_name: str
    parameter_value: float
    habit_branch: int
    dilatational_factor: float
    true_invariant_plane: bool
    pre_shape_deformation: Array
    habit_rotation: Array
    macroscopic_deformation: Array
    rank_one_vector: Array
    habit_normal_parent_cartesian: Array
    habit_plane_parent_crystal: Array
    habit_plane_product_crystal_base: Array
    shape_vector_magnitude: float
    tangential_shape_shear_vector: Array
    tangential_shape_shear_magnitude: float
    normal_shape_component: float
    lattice_invariant_shear_magnitude: float
    base_variant_volume_fraction: float | None
    other_variant_volume_fraction: float | None
    or_parent_from_product_base_symmetric: Array
    or_parent_from_product_base_ptclab: Array
    or_parent_from_product_other_symmetric: Array | None
    or_parent_from_product_other_ptclab: Array | None
    invariant_line: PTMCInvariantLine | None
    middle_stretch_residual: float
    rank_one_residual: float
    rotation_orthogonality_residual: float
    rotation_determinant: float
    or_base_residual: float
    or_other_residual: float | None


@dataclass(frozen=True)
class PTMCContinuousFamily:
    """An exact continuum of compatible LIS parameters."""

    lis_type: str
    base_variant_index: int
    other_variant_index: int | None
    twin_branch: int | None
    parameter_name: str
    domain: tuple[float, float] | None
    dilatational_factor: float
    polynomial_coefficients_ascending: tuple[float, float, float]
    polynomial_verification_residual: float
    note: str


@dataclass(frozen=True)
class PTMCAudit:
    maximum_variant_metric_residual: float
    maximum_variant_polar_residual: float
    maximum_twin_rank_one_residual: float
    maximum_habit_rank_one_residual: float
    maximum_habit_rotation_residual: float
    maximum_or_residual: float
    maximum_middle_stretch_residual: float
    maximum_parameter_polynomial_residual: float

    @property
    def maximum_residual(self) -> float:
        return max(
            self.maximum_variant_metric_residual,
            self.maximum_variant_polar_residual,
            self.maximum_twin_rank_one_residual,
            self.maximum_habit_rank_one_residual,
            self.maximum_habit_rotation_residual,
            self.maximum_or_residual,
            self.maximum_middle_stretch_residual,
            self.maximum_parameter_polynomial_residual,
        )


@dataclass(frozen=True)
class PTMCReport:
    transformation_id: str
    parent_phase_id: str
    product_phase_id: str
    lis_type: str
    dilatational_factor: float
    variants: tuple[PTMCVariant, ...]
    twin_relations: tuple[PTMCTwinRelation, ...]
    parameter_roots: tuple[PTMCParameterRoots, ...]
    solutions: tuple[PTMCHabitSolution, ...]
    continuous_families: tuple[PTMCContinuousFamily, ...]
    full_parent_symmetry_order: int
    proper_parent_symmetry_order: int
    full_product_symmetry_order: int
    proper_product_symmetry_order: int
    audit: PTMCAudit
    notes: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-ready report without changing scientific values."""

        def convert(value: Any) -> Any:
            if isinstance(value, np.ndarray):
                return value.tolist()
            if isinstance(value, np.generic):
                return value.item()
            if isinstance(value, tuple):
                return [convert(item) for item in value]
            if isinstance(value, list):
                return [convert(item) for item in value]
            if isinstance(value, dict):
                return {key: convert(item) for key, item in value.items()}
            return value

        return convert(asdict(self))


@dataclass(frozen=True)
class PTMCSlipSystemInput:
    """PTCLab-style slip LIS input in product crystal coordinates."""

    plane_product: tuple[float, float, float]
    direction_product: tuple[float, float, float]
    base_variant_index: int | None = None
    max_abs_shear: float | None = None

    def __post_init__(self) -> None:
        p = np.asarray(self.plane_product, dtype=float).reshape(3)
        d = np.asarray(self.direction_product, dtype=float).reshape(3)
        if not np.all(np.isfinite(p)) or not np.all(np.isfinite(d)):
            raise ValueError("Slip plane/direction must be finite")
        if float(np.linalg.norm(p)) <= 1.0e-15:
            raise ValueError("Slip plane must be nonzero")
        if float(np.linalg.norm(d)) <= 1.0e-15:
            raise ValueError("Slip direction must be nonzero")
        incidence_scale = max(float(np.linalg.norm(p) * np.linalg.norm(d)), 1.0)
        if abs(float(p @ d)) / incidence_scale > 1.0e-10:
            raise ValueError(
                "Slip direction must lie in the slip plane: (hkl)·[uvw] must be zero"
            )
        if self.max_abs_shear is not None and self.max_abs_shear <= 0.0:
            raise ValueError("max_abs_shear must be positive when supplied")
        if self.base_variant_index is not None and self.base_variant_index < 0:
            raise ValueError("base_variant_index must be >= 0")


@dataclass(frozen=True)
class PTMCTwinPlaneInput:
    """PTCLab-style twin-plane selection in product crystal coordinates.

    The shear direction is not requested from the user.  It is obtained by
    independently enumerating exact M/M rank-one twin relations and matching
    their deformed twin plane to the supplied product plane.
    """

    plane_product: tuple[float, float, float]
    base_variant_index: int | None = None
    plane_tolerance_deg: float = 1.0e-5

    def __post_init__(self) -> None:
        p = np.asarray(self.plane_product, dtype=float).reshape(3)
        if not np.all(np.isfinite(p)) or float(np.linalg.norm(p)) <= 1.0e-15:
            raise ValueError("Twin plane must be a finite nonzero (hkl)")
        if self.base_variant_index is not None and self.base_variant_index < 0:
            raise ValueError("base_variant_index must be >= 0")
        if self.plane_tolerance_deg <= 0.0:
            raise ValueError("plane_tolerance_deg must be positive")


@dataclass(frozen=True)
class PTMCTwinPairInput:
    """Advanced exact selection of a stretch-variant pair."""

    base_variant_index: int
    other_variant_index: int
    branch: int | None = None

    def __post_init__(self) -> None:
        if self.base_variant_index < 0 or self.other_variant_index < 0:
            raise ValueError("Variant indices must be >= 0")
        if self.base_variant_index == self.other_variant_index:
            raise ValueError("Twin pair must contain two distinct variants")
        if self.branch not in {None, -1, 1}:
            raise ValueError("branch must be None, -1 or +1")


@dataclass(frozen=True)
class _RankOneBranch:
    branch: int
    rotation: Array
    a: Array
    n: Array
    eigenvalues_relative_cauchy_green: Array
    outer_product_residual: float
    rotation_orthogonality_residual: float
    rotation_determinant: float
    maximum_residual: float


def _relative_residual(lhs: Array, rhs: Array) -> float:
    left = np.asarray(lhs, dtype=float)
    right = np.asarray(rhs, dtype=float)
    scale = max(float(np.linalg.norm(left)), float(np.linalg.norm(right)), 1.0)
    return float(np.linalg.norm(left - right) / scale)


def _validated_spd(matrix: Array, *, name: str) -> Array:
    value = np.asarray(matrix, dtype=float)
    if value.shape != (3, 3) or not np.all(np.isfinite(value)):
        raise ValueError(f"{name} must be a finite 3x3 matrix")
    symmetric = 0.5 * (value + value.T)
    if _relative_residual(value, symmetric) > 1.0e-12:
        raise ValueError(f"{name} must be symmetric")
    eigenvalues = np.linalg.eigvalsh(symmetric)
    if float(np.min(eigenvalues)) <= 0.0:
        raise ValueError(f"{name} must be positive definite; eigenvalues={eigenvalues}")
    return symmetric


def _validated_invertible(matrix: Array, *, name: str) -> Array:
    value = np.asarray(matrix, dtype=float)
    if value.shape != (3, 3) or not np.all(np.isfinite(value)):
        raise ValueError(f"{name} must be a finite 3x3 matrix")
    determinant = float(np.linalg.det(value))
    if abs(determinant) <= 1.0e-14:
        raise ValueError(f"{name} must be invertible")
    return value


def _spd_sqrt(matrix: Array) -> Array:
    value = _validated_spd(matrix, name="SPD matrix")
    eigenvalues, eigenvectors = np.linalg.eigh(value)
    return (eigenvectors * np.sqrt(eigenvalues)) @ eigenvectors.T


def _unit(vector: Array, *, name: str) -> Array:
    value = np.asarray(vector, dtype=float).reshape(3)
    if not np.all(np.isfinite(value)):
        raise ValueError(f"{name} contains non-finite values")
    norm = float(np.linalg.norm(value))
    if norm <= 1.0e-15:
        raise ValueError(f"{name} must be nonzero")
    return value / norm


def _proper_rotation_residual(rotation: Array) -> tuple[float, float, float]:
    value = np.asarray(rotation, dtype=float).reshape(3, 3)
    orthogonality = float(np.linalg.norm(value.T @ value - np.eye(3), ord="fro"))
    determinant = float(np.linalg.det(value))
    return max(orthogonality, abs(determinant - 1.0)), orthogonality, determinant


def _projective_angle_deg(first: Array, second: Array) -> float:
    left = _unit(first, name="first vector")
    right = _unit(second, name="second vector")
    cosine = float(np.clip(abs(left @ right), 0.0, 1.0))
    return float(np.degrees(np.arccos(cosine)))


def _projective_coefficients(vector: Array, *, tolerance: float = 1.0e-14) -> Array:
    value = np.asarray(vector, dtype=float).reshape(3)
    scale = float(np.max(np.abs(value)))
    if scale <= tolerance:
        raise ValueError("Cannot projectively normalize a zero vector")
    result = value / scale
    first = next((item for item in result if abs(item) > tolerance), 1.0)
    if first < 0.0:
        result = -result
    result[np.abs(result) < tolerance] = 0.0
    return result


def _correspondence_array(value: Correspondence | Array) -> Array:
    if isinstance(value, Correspondence):
        return _validated_invertible(
            np.asarray(value.C_M_from_A, dtype=float),
            name="correspondence",
        )
    return _validated_invertible(value, name="correspondence")


def _validated_operations(
    operations: Iterable[Array],
    metric: Array,
    *,
    name: str,
    tolerance: float,
) -> tuple[Array, ...]:
    M = _validated_spd(metric, name=f"{name} metric")
    output: list[Array] = []
    for index, operation in enumerate(operations):
        matrix = _validated_invertible(operation, name=f"{name} symmetry[{index}]")
        residual = _relative_residual(matrix.T @ M @ matrix, M)
        if residual > tolerance:
            raise ValueError(
                f"{name} symmetry[{index}] does not preserve the supplied metric; "
                f"residual={residual:.3e}"
            )
        output.append(matrix)
    if not output:
        raise ValueError(f"{name} symmetry group must contain at least identity")
    return tuple(output)


def _point_group_operations_for_lattice(
    symbol: str,
    lattice: Lattice,
    *,
    tolerance: float,
) -> tuple[Array, ...]:
    operations = tuple(
        np.asarray(operation, dtype=float)
        for operation in point_group_operations(symbol)
    )
    return _validated_operations(
        operations,
        lattice.metric(),
        name=f"point group {symbol!r}",
        tolerance=tolerance,
    )


def _rank_one_connections(
    F_other: Array,
    F_base: Array,
    *,
    eigenvalue_tolerance: float,
) -> tuple[_RankOneBranch, ...]:
    """Independently solve R F_other - F_base = a⊗n.

    This is the standard rank-one compatibility proposition, reproduced here
    inside the PTMC theory adapter so PTMC does not consume BallJamesAdapter
    outputs.
    """

    other = _validated_invertible(F_other, name="F_other")
    base = _validated_invertible(F_base, name="F_base")
    if float(np.linalg.det(other)) <= 0.0 or float(np.linalg.det(base)) <= 0.0:
        raise ValueError("PTMC deformation gradients must be orientation preserving")

    relative_deformation = other @ np.linalg.inv(base)
    cauchy_green = 0.5 * (
        relative_deformation.T @ relative_deformation
        + (relative_deformation.T @ relative_deformation).T
    )
    eigenvalues, eigenvectors = np.linalg.eigh(cauchy_green)
    order = np.argsort(eigenvalues)
    mu = np.asarray(eigenvalues[order], dtype=float)
    vectors = np.asarray(eigenvectors[:, order], dtype=float)
    mu1, mu2, mu3 = (float(item) for item in mu)

    if mu1 <= 0.0 or abs(mu2 - 1.0) > eigenvalue_tolerance:
        return ()
    if np.linalg.norm(cauchy_green - np.eye(3), ord="fro") <= eigenvalue_tolerance:
        return ()
    if mu3 - mu1 <= eigenvalue_tolerance:
        return ()
    if mu1 > 1.0 + eigenvalue_tolerance or mu3 < 1.0 - eigenvalue_tolerance:
        return ()

    one_minus_mu1 = max(0.0, 1.0 - mu1)
    mu3_minus_one = max(0.0, mu3 - 1.0)
    denominator = float(np.sqrt(mu3 - mu1))
    e1 = vectors[:, 0]
    e3 = vectors[:, 2]

    output: list[_RankOneBranch] = []
    for branch in (-1, 1):
        b = (
            np.sqrt(mu3 * one_minus_mu1) * e1
            + branch * np.sqrt(mu1 * mu3_minus_one) * e3
        ) / denominator
        m = (
            (np.sqrt(mu3) - np.sqrt(mu1))
            / denominator
            * (-np.sqrt(one_minus_mu1) * e1 + branch * np.sqrt(mu3_minus_one) * e3)
        )
        rotation = (np.eye(3) + np.outer(b, m)) @ np.linalg.inv(relative_deformation)
        n = base.T @ m
        n_norm = float(np.linalg.norm(n))
        if n_norm <= 1.0e-15:
            raise AssertionError("Rank-one branch produced a zero interface normal")
        normal = n / n_norm
        vector = b * n_norm

        difference = rotation @ other - base
        outer_residual = _relative_residual(
            difference,
            np.outer(vector, normal),
        )
        maximum_rotation, orthogonality, determinant = _proper_rotation_residual(
            rotation
        )
        output.append(
            _RankOneBranch(
                branch=branch,
                rotation=rotation,
                a=vector,
                n=normal,
                eigenvalues_relative_cauchy_green=mu.copy(),
                outer_product_residual=outer_residual,
                rotation_orthogonality_residual=orthogonality,
                rotation_determinant=determinant,
                maximum_residual=max(outer_residual, maximum_rotation),
            )
        )
    return tuple(output)


def _middle_singular_value(matrix: Array) -> float:
    values = np.sort(np.linalg.svd(np.asarray(matrix, dtype=float), compute_uv=False))
    return float(values[1])


def _quadratic_value(
    coefficients_ascending: tuple[float, float, float],
    x: float,
) -> float:
    c0, c1, c2 = coefficients_ascending
    return float(c0 + c1 * x + c2 * x * x)


def _stable_quadratic_roots(
    c0: float,
    c1: float,
    c2: float,
    *,
    tolerance: float,
) -> tuple[float, ...]:
    scale = max(abs(c0), abs(c1), abs(c2), 1.0)
    threshold = tolerance * scale
    if abs(c2) <= threshold:
        if abs(c1) <= threshold:
            return ()
        return (-c0 / c1,)

    discriminant = c1 * c1 - 4.0 * c2 * c0
    discriminant_scale = max(c1 * c1, abs(4.0 * c2 * c0), 1.0)
    if discriminant < -tolerance * discriminant_scale:
        return ()
    discriminant = max(0.0, discriminant)
    root_discriminant = float(np.sqrt(discriminant))
    if root_discriminant <= tolerance * max(abs(c1), 1.0):
        return (-c1 / (2.0 * c2),)

    sign = 1.0 if c1 >= 0.0 else -1.0
    q = -0.5 * (c1 + sign * root_discriminant)
    first = q / c2
    second = c0 / q if abs(q) > threshold else (-c1 - root_discriminant) / (2.0 * c2)
    roots = sorted((float(first), float(second)))
    if abs(roots[1] - roots[0]) <= 10.0 * tolerance * max(
        abs(roots[0]),
        abs(roots[1]),
        1.0,
    ):
        return (0.5 * (roots[0] + roots[1]),)
    return tuple(roots)


def solve_affine_ptmc_parameters(
    F0: Array,
    rank_one_increment: Array,
    *,
    dilatational_factor: float = 1.0,
    parameter_name: str = "parameter",
    domain: tuple[float, float] | None = None,
    polynomial_tolerance: float = 1.0e-10,
    middle_stretch_tolerance: float = 1.0e-7,
) -> PTMCParameterRoots:
    r"""Solve the classical PTMC single-shear parameter exactly as a quadratic.

    ``F(x)=F0+x A`` with rank-one ``A``.  Compatibility with a uniformly
    dilated parent plane requires

        det(F(x)^T F(x) - delta^2 I) = 0

    and the *middle* singular value of F(x) to equal ``delta``.

    For rank-one A the determinant polynomial is at most quadratic.  The code
    reconstructs it from x=-1,0,1 and independently verifies the polynomial at
    additional points before accepting any roots.
    """

    base = _validated_invertible(F0, name="F0")
    increment = np.asarray(rank_one_increment, dtype=float)
    if increment.shape != (3, 3) or not np.all(np.isfinite(increment)):
        raise ValueError("rank_one_increment must be a finite 3x3 matrix")
    singular_values = np.linalg.svd(increment, compute_uv=False)
    if singular_values[0] <= 1.0e-15:
        raise ValueError("rank_one_increment must be nonzero")
    if max(float(singular_values[1]), float(singular_values[2])) > (
        1.0e-9 * max(float(singular_values[0]), 1.0)
    ):
        raise ValueError("rank_one_increment must have numerical rank one")
    if dilatational_factor <= 0.0 or not np.isfinite(dilatational_factor):
        raise ValueError("dilatational_factor must be finite and positive")
    if polynomial_tolerance <= 0.0 or middle_stretch_tolerance <= 0.0:
        raise ValueError("PTMC numerical tolerances must be positive")
    if domain is not None:
        lower, upper = map(float, domain)
        if not np.isfinite(lower) or not np.isfinite(upper) or lower > upper:
            raise ValueError("domain must be a finite ordered interval")
        domain = (lower, upper)

    delta2 = float(dilatational_factor) ** 2

    def determinant_condition(x: float) -> float:
        deformation = base + float(x) * increment
        matrix = deformation.T @ deformation - delta2 * np.eye(3)
        return float(np.linalg.det(matrix))

    y_minus = determinant_condition(-1.0)
    y_zero = determinant_condition(0.0)
    y_plus = determinant_condition(1.0)
    c0 = y_zero
    c1 = 0.5 * (y_plus - y_minus)
    c2 = 0.5 * (y_plus + y_minus) - y_zero
    coefficients = (float(c0), float(c1), float(c2))

    verification_points = (-0.625, 0.375, 1.75)
    verification_errors = []
    for x in verification_points:
        exact = determinant_condition(x)
        predicted = _quadratic_value(coefficients, x)
        verification_errors.append(abs(exact - predicted))
    polynomial_scale = max(
        abs(y_minus),
        abs(y_zero),
        abs(y_plus),
        *(abs(determinant_condition(x)) for x in verification_points),
        1.0,
    )
    verification_residual = max(verification_errors) / polynomial_scale
    if verification_residual > 100.0 * polynomial_tolerance:
        raise AssertionError(
            "PTMC single-shear determinant failed the quadratic audit; "
            f"relative residual={verification_residual:.3e}"
        )

    coefficient_scale = max(abs(c0), abs(c1), abs(c2), 1.0)
    continuum = max(abs(c0), abs(c1), abs(c2)) <= (
        polynomial_tolerance * coefficient_scale
    )
    roots: list[float] = []
    if not continuum:
        for root in _stable_quadratic_roots(
            c0,
            c1,
            c2,
            tolerance=polynomial_tolerance,
        ):
            if domain is not None and not (
                domain[0] - polynomial_tolerance
                <= root
                <= domain[1] + polynomial_tolerance
            ):
                continue
            if domain is not None:
                root = min(domain[1], max(domain[0], root))
            deformation = base + root * increment
            middle_residual = abs(
                _middle_singular_value(deformation) - dilatational_factor
            )
            if middle_residual > middle_stretch_tolerance:
                continue
            if not any(
                abs(root - existing)
                <= 100.0 * polynomial_tolerance * max(abs(root), abs(existing), 1.0)
                for existing in roots
            ):
                roots.append(float(root))
    roots.sort()

    nearest_parameter: float | None = None
    nearest_residual: float | None = None
    if domain is not None and not continuum:

        def objective(x: float) -> float:
            return abs(
                _middle_singular_value(base + float(x) * increment)
                - dilatational_factor
            )

        candidates = [
            (domain[0], objective(domain[0])),
            (domain[1], objective(domain[1])),
        ]
        if domain[1] > domain[0]:
            minimization = minimize_scalar(
                objective,
                bounds=domain,
                method="bounded",
                options={"xatol": 1.0e-12},
            )
            if minimization.success:
                candidates.append((float(minimization.x), float(minimization.fun)))
        nearest_parameter, nearest_residual = min(candidates, key=lambda item: item[1])

    return PTMCParameterRoots(
        parameter_name=parameter_name,
        discrete_roots=tuple(roots),
        continuum=continuum,
        domain=domain,
        polynomial_coefficients_ascending=coefficients,
        polynomial_verification_residual=float(verification_residual),
        nearest_parameter=nearest_parameter,
        nearest_middle_stretch_residual=nearest_residual,
    )


def _build_variants(
    M_a: Array,
    M_m: Array,
    correspondence: Array,
    parent_symmetry: tuple[Array, ...],
    *,
    algebraic_tolerance: float,
) -> tuple[PTMCVariant, ...]:
    parent = _validated_spd(M_a, name="M_a")
    product = _validated_spd(M_m, name="M_m")
    C0 = _validated_invertible(correspondence, name="correspondence")
    B_a = _spd_sqrt(parent)
    B_m = _spd_sqrt(product)
    B_a_inv = np.linalg.inv(B_a)

    unique: list[dict[str, Any]] = []
    for symmetry_index, operation in enumerate(parent_symmetry):
        g = np.asarray(operation, dtype=float).reshape(3, 3)
        if float(np.linalg.det(g)) <= 0.0:
            continue
        Q = B_a @ g @ B_a_inv
        q_residual, _, _ = _proper_rotation_residual(Q)
        if q_residual > 100.0 * algebraic_tolerance:
            raise ValueError(
                "A proper parent crystallographic symmetry did not become SO(3) "
                f"in the metric frame; index={symmetry_index}, residual={q_residual:.3e}"
            )

        C_i = C0 @ np.linalg.inv(g)
        F_correspondence = B_m @ C_i @ B_a_inv
        if float(np.linalg.det(F_correspondence)) <= 0.0:
            raise ValueError(
                "The selected correspondence variant reverses orientation. "
                "PTMC requires an orientation-preserving lattice deformation; "
                f"parent symmetry index={symmetry_index}."
            )
        target = 0.5 * (
            F_correspondence.T @ F_correspondence
            + (F_correspondence.T @ F_correspondence).T
        )
        U = _spd_sqrt(target)
        R_polar = F_correspondence @ np.linalg.inv(U)
        polar_residual, _, _ = _proper_rotation_residual(R_polar)
        metric_residual = _relative_residual(U @ U, target)

        match = next(
            (
                item
                for item in unique
                if np.linalg.norm(U - item["U"], ord="fro")
                <= 100.0 * algebraic_tolerance
            ),
            None,
        )
        if match is None:
            unique.append(
                {
                    "U": U,
                    "C": C_i,
                    "rep": symmetry_index,
                    "indices": [symmetry_index],
                    "R_polar": R_polar,
                    "audit": max(metric_residual, polar_residual),
                }
            )
        else:
            match["indices"].append(symmetry_index)
            match["audit"] = max(
                float(match["audit"]),
                metric_residual,
                polar_residual,
            )

    variants: list[PTMCVariant] = []
    for index, item in enumerate(unique):
        U = np.asarray(item["U"], dtype=float)
        stretches = np.sort(np.linalg.eigvalsh(U))
        variants.append(
            PTMCVariant(
                index=index,
                U=U,
                correspondence_M_from_A=np.asarray(item["C"], dtype=float),
                representative_parent_symmetry_index=int(item["rep"]),
                generating_parent_symmetry_indices=tuple(
                    int(value) for value in item["indices"]
                ),
                polar_rotation_product_from_parent=np.asarray(
                    item["R_polar"],
                    dtype=float,
                ),
                principal_stretches=stretches,
                determinant=float(np.linalg.det(U)),
                maximum_audit_residual=float(item["audit"]),
            )
        )
    if not variants:
        raise ValueError("No proper parent symmetry generated a PTMC stretch variant")
    return tuple(variants)


def _enumerate_twin_relations(
    variants: tuple[PTMCVariant, ...],
    product_metric: Array,
    *,
    eigenvalue_tolerance: float,
) -> tuple[PTMCTwinRelation, ...]:
    B_m = _spd_sqrt(product_metric)
    relations: list[PTMCTwinRelation] = []
    for base in variants:
        for other in variants:
            if base.index == other.index:
                continue
            for branch in _rank_one_connections(
                other.U,
                base.U,
                eigenvalue_tolerance=eigenvalue_tolerance,
            ):
                current_normal = _unit(
                    np.linalg.solve(base.U.T, branch.n),
                    name="deformed twin-plane normal",
                )
                product_normal = (
                    base.polar_rotation_product_from_parent @ current_normal
                )
                product_plane = _projective_coefficients(B_m.T @ product_normal)
                shear = float(
                    np.linalg.norm(np.linalg.solve(base.U.T, branch.n))
                    * np.linalg.norm(branch.a)
                )
                relations.append(
                    PTMCTwinRelation(
                        base_variant_index=base.index,
                        other_variant_index=other.index,
                        branch=branch.branch,
                        rotation_hat=branch.rotation,
                        a=branch.a,
                        n_reference=branch.n,
                        deformed_twin_plane_normal_base=current_normal,
                        twin_plane_product_crystal_base=product_plane,
                        twin_shear_magnitude=shear,
                        rank_one_residual=branch.outer_product_residual,
                        rotation_residual=max(
                            branch.rotation_orthogonality_residual,
                            abs(branch.rotation_determinant - 1.0),
                        ),
                    )
                )
    return tuple(relations)


def _frame_rotation_to_ptclab(lattice: Lattice) -> Array:
    B_symmetric = _spd_sqrt(lattice.metric())
    B_ptclab = lattice.structure_matrix()
    rotation = B_ptclab @ np.linalg.inv(B_symmetric)
    maximum, _, determinant = _proper_rotation_residual(rotation)
    if maximum > 1.0e-8:
        raise AssertionError(
            "Symmetric-metric to PTCLab frame bridge is not a proper rotation; "
            f"residual={maximum:.3e}, det={determinant:.12g}"
        )
    return rotation


def _or_to_ptclab(
    R_parent_from_product_symmetric: Array,
    parent_lattice: Lattice,
    product_lattice: Lattice,
) -> Array:
    Q_a = _frame_rotation_to_ptclab(parent_lattice)
    Q_m = _frame_rotation_to_ptclab(product_lattice)
    result = Q_a @ np.asarray(R_parent_from_product_symmetric, dtype=float) @ Q_m.T
    maximum, _, determinant = _proper_rotation_residual(result)
    if maximum > 1.0e-8:
        raise AssertionError(
            "PTMC OR conversion to PTCLab frames lost SO(3); "
            f"residual={maximum:.3e}, det={determinant:.12g}"
        )
    return result


def _product_plane_physical_normal(
    plane_product: Array,
    product_metric: Array,
) -> Array:
    B_m = _spd_sqrt(product_metric)
    return _unit(
        np.linalg.solve(B_m.T, np.asarray(plane_product, dtype=float).reshape(3)),
        name="product plane normal",
    )


def _product_direction_physical(
    direction_product: Array,
    product_metric: Array,
) -> Array:
    B_m = _spd_sqrt(product_metric)
    return _unit(
        B_m @ np.asarray(direction_product, dtype=float).reshape(3),
        name="product direction",
    )


def _habit_solution_from_predeformation(
    *,
    lis_type: LISType,
    base_variant: PTMCVariant,
    other_variant: PTMCVariant | None,
    twin_relation: PTMCTwinRelation | None,
    parameter_name: str,
    parameter_value: float,
    lattice_invariant_shear_magnitude: float,
    F_pre: Array,
    lis_plane_normal_pre_habit: Array,
    parent_lattice: Lattice,
    product_lattice: Lattice,
    dilatational_factor: float,
    eigenvalue_tolerance: float,
) -> tuple[PTMCHabitSolution, ...]:
    delta_identity = float(dilatational_factor) * np.eye(3)
    habit_branches = _rank_one_connections(
        F_pre,
        delta_identity,
        eigenvalue_tolerance=eigenvalue_tolerance,
    )
    B_a = _spd_sqrt(parent_lattice.metric())
    B_a_inv = np.linalg.inv(B_a)
    B_m = _spd_sqrt(product_lattice.metric())

    solutions: list[PTMCHabitSolution] = []
    for habit in habit_branches:
        shape_deformation = habit.rotation @ F_pre
        middle_residual = abs(_middle_singular_value(F_pre) - dilatational_factor)
        habit_normal = _unit(habit.n, name="habit-plane normal")
        habit_plane_parent = _projective_coefficients(B_a.T @ habit_normal)
        shape_vector = np.asarray(habit.a, dtype=float)
        normal_component = float(shape_vector @ habit_normal)
        tangential = shape_vector - normal_component * habit_normal

        or_base = habit.rotation @ base_variant.polar_rotation_product_from_parent.T
        or_base_residual, _, _ = _proper_rotation_residual(or_base)
        or_base_ptclab = _or_to_ptclab(
            or_base,
            parent_lattice,
            product_lattice,
        )
        product_normal_base = or_base.T @ habit_normal
        habit_plane_product_base = _projective_coefficients(B_m.T @ product_normal_base)

        or_other: Array | None = None
        or_other_ptclab: Array | None = None
        or_other_residual: float | None = None
        if other_variant is not None and twin_relation is not None:
            or_other = (
                habit.rotation
                @ twin_relation.rotation_hat
                @ other_variant.polar_rotation_product_from_parent.T
            )
            or_other_residual, _, _ = _proper_rotation_residual(or_other)
            or_other_ptclab = _or_to_ptclab(
                or_other,
                parent_lattice,
                product_lattice,
            )

        rotated_lis_normal = _unit(
            habit.rotation
            @ _unit(
                lis_plane_normal_pre_habit,
                name="LIS plane normal",
            ),
            name="rotated LIS plane normal",
        )
        line_vector = np.cross(habit_normal, rotated_lis_normal)
        invariant_line: PTMCInvariantLine | None = None
        if float(np.linalg.norm(line_vector)) > 1.0e-12:
            line_parent = _unit(line_vector, name="invariant line")
            expected = dilatational_factor * line_parent
            deformation_residual = float(
                np.linalg.norm(shape_deformation @ line_parent - expected)
            )
            line_parent_crystal = _projective_coefficients(B_a_inv @ line_parent)
            line_product_crystal = _projective_coefficients(
                np.linalg.solve(B_m, or_base.T @ line_parent)
            )
            invariant_line = PTMCInvariantLine(
                parent_cartesian=line_parent,
                parent_crystal=line_parent_crystal,
                product_crystal_base=line_product_crystal,
                deformation_residual=deformation_residual,
            )

        base_fraction: float | None = None
        other_fraction: float | None = None
        if lis_type is LISType.TWIN:
            other_fraction = float(parameter_value)
            base_fraction = 1.0 - other_fraction

        solutions.append(
            PTMCHabitSolution(
                lis_type=lis_type.value,
                base_variant_index=base_variant.index,
                other_variant_index=(
                    other_variant.index if other_variant is not None else None
                ),
                twin_branch=(
                    twin_relation.branch if twin_relation is not None else None
                ),
                parameter_name=parameter_name,
                parameter_value=float(parameter_value),
                habit_branch=habit.branch,
                dilatational_factor=float(dilatational_factor),
                true_invariant_plane=abs(dilatational_factor - 1.0)
                <= eigenvalue_tolerance,
                pre_shape_deformation=np.asarray(F_pre, dtype=float),
                habit_rotation=habit.rotation,
                macroscopic_deformation=shape_deformation,
                rank_one_vector=shape_vector,
                habit_normal_parent_cartesian=habit_normal,
                habit_plane_parent_crystal=habit_plane_parent,
                habit_plane_product_crystal_base=habit_plane_product_base,
                shape_vector_magnitude=float(np.linalg.norm(shape_vector)),
                tangential_shape_shear_vector=tangential,
                tangential_shape_shear_magnitude=float(np.linalg.norm(tangential)),
                normal_shape_component=normal_component,
                lattice_invariant_shear_magnitude=float(
                    lattice_invariant_shear_magnitude
                ),
                base_variant_volume_fraction=base_fraction,
                other_variant_volume_fraction=other_fraction,
                or_parent_from_product_base_symmetric=or_base,
                or_parent_from_product_base_ptclab=or_base_ptclab,
                or_parent_from_product_other_symmetric=or_other,
                or_parent_from_product_other_ptclab=or_other_ptclab,
                invariant_line=invariant_line,
                middle_stretch_residual=middle_residual,
                rank_one_residual=habit.outer_product_residual,
                rotation_orthogonality_residual=habit.rotation_orthogonality_residual,
                rotation_determinant=habit.rotation_determinant,
                or_base_residual=or_base_residual,
                or_other_residual=or_other_residual,
            )
        )
    return tuple(solutions)


def _base_notes() -> tuple[str, ...]:
    return (
        (
            "PTMC is computed independently from Cayron CT/CMC/SMC and does not consume "
            "BallJamesAdapter outputs."
        ),
        (
            "The common front-end inputs are the two crystal cells, point groups and lattice "
            "correspondence; only the lattice-invariant-shear specification is PTMC-specific."
        ),
        (
            "All discrete single-shear roots are retained. Exact continuum compatibility is "
            "reported as a continuum family and is never replaced by an arbitrary sample."
        ),
        "No rounded experimental state is silently projected to exact compatibility.",
        (
            "For delta=1 the reported habit plane is a true invariant plane. For delta!=1 it "
            "is the Bowles-Mackenzie uniformly dilated-plane extension."
        ),
        (
            "OR matrices are exposed in both symmetric-metric and PTCLab conventional "
            "Cartesian frames; crystal-plane/direction indices are frame independent."
        ),
    )


def _build_report(
    *,
    transformation_id: str,
    parent_phase_id: str,
    product_phase_id: str,
    lis_type: LISType,
    dilatational_factor: float,
    variants: tuple[PTMCVariant, ...],
    twin_relations: tuple[PTMCTwinRelation, ...],
    parameter_roots: list[PTMCParameterRoots],
    solutions: list[PTMCHabitSolution],
    continuous_families: list[PTMCContinuousFamily],
    full_parent_symmetry_order: int,
    proper_parent_symmetry_order: int,
    full_product_symmetry_order: int,
    proper_product_symmetry_order: int,
) -> PTMCReport:
    variant_metric = [item.maximum_audit_residual for item in variants]
    variant_polar = [
        _proper_rotation_residual(item.polar_rotation_product_from_parent)[0]
        for item in variants
    ]
    twin_residual = [
        max(item.rank_one_residual, item.rotation_residual) for item in twin_relations
    ]
    habit_rank_one = [item.rank_one_residual for item in solutions]
    habit_rotation = [
        max(
            item.rotation_orthogonality_residual,
            abs(item.rotation_determinant - 1.0),
        )
        for item in solutions
    ]
    or_residual = [
        max(
            item.or_base_residual,
            item.or_other_residual or 0.0,
        )
        for item in solutions
    ]
    middle = [item.middle_stretch_residual for item in solutions]
    polynomial = [item.polynomial_verification_residual for item in parameter_roots]
    audit = PTMCAudit(
        maximum_variant_metric_residual=max(variant_metric, default=0.0),
        maximum_variant_polar_residual=max(variant_polar, default=0.0),
        maximum_twin_rank_one_residual=max(twin_residual, default=0.0),
        maximum_habit_rank_one_residual=max(habit_rank_one, default=0.0),
        maximum_habit_rotation_residual=max(habit_rotation, default=0.0),
        maximum_or_residual=max(or_residual, default=0.0),
        maximum_middle_stretch_residual=max(middle, default=0.0),
        maximum_parameter_polynomial_residual=max(polynomial, default=0.0),
    )
    return PTMCReport(
        transformation_id=transformation_id,
        parent_phase_id=parent_phase_id,
        product_phase_id=product_phase_id,
        lis_type=lis_type.value,
        dilatational_factor=float(dilatational_factor),
        variants=variants,
        twin_relations=twin_relations,
        parameter_roots=tuple(parameter_roots),
        solutions=tuple(solutions),
        continuous_families=tuple(continuous_families),
        full_parent_symmetry_order=int(full_parent_symmetry_order),
        proper_parent_symmetry_order=int(proper_parent_symmetry_order),
        full_product_symmetry_order=int(full_product_symmetry_order),
        proper_product_symmetry_order=int(proper_product_symmetry_order),
        audit=audit,
        notes=_base_notes(),
    )


def analyze_ptmc_twinning(
    parent_lattice: Lattice,
    product_lattice: Lattice,
    correspondence: Correspondence | Array,
    parent_symmetry_matrices: Iterable[Array],
    product_symmetry_matrices: Iterable[Array],
    *,
    twin_plane: PTMCTwinPlaneInput | None = None,
    twin_pair: PTMCTwinPairInput | None = None,
    base_variant_index: int | None = None,
    dilatational_factor: float = 1.0,
    transformation_id: str = "manual_ptmc",
    parent_phase_id: str = "parent",
    product_phase_id: str = "product",
    algebraic_tolerance: float = 1.0e-10,
    eigenvalue_tolerance: float = 1.0e-8,
    middle_stretch_tolerance: float = 1.0e-7,
    polynomial_tolerance: float = 1.0e-10,
) -> PTMCReport:
    """Enumerate classical twinning-PTMC branches.

    With neither ``twin_plane`` nor ``twin_pair`` supplied, every exact M/M
    rank-one relation is considered.  ``base_variant_index`` can restrict this
    exhaustive search without changing the mathematical model.
    """

    if twin_plane is not None and twin_pair is not None:
        raise ValueError("Supply at most one of twin_plane or twin_pair")
    if dilatational_factor <= 0.0:
        raise ValueError("dilatational_factor must be positive")

    parent_metric = parent_lattice.metric()
    product_metric = product_lattice.metric()
    parent_symmetry = _validated_operations(
        parent_symmetry_matrices,
        parent_metric,
        name="parent",
        tolerance=max(algebraic_tolerance, 1.0e-9),
    )
    product_symmetry = _validated_operations(
        product_symmetry_matrices,
        product_metric,
        name="product",
        tolerance=max(algebraic_tolerance, 1.0e-9),
    )
    C = _correspondence_array(correspondence)
    variants = _build_variants(
        parent_metric,
        product_metric,
        C,
        parent_symmetry,
        algebraic_tolerance=algebraic_tolerance,
    )
    twin_relations_all = _enumerate_twin_relations(
        variants,
        product_metric,
        eigenvalue_tolerance=eigenvalue_tolerance,
    )

    selected = list(twin_relations_all)
    selected_base = base_variant_index
    if twin_plane is not None and twin_plane.base_variant_index is not None:
        if selected_base is not None and selected_base != twin_plane.base_variant_index:
            raise ValueError("Conflicting base_variant_index selections")
        selected_base = twin_plane.base_variant_index
    if twin_pair is not None:
        if selected_base is not None and selected_base != twin_pair.base_variant_index:
            raise ValueError("Conflicting base_variant_index selections")
        selected_base = twin_pair.base_variant_index

    if selected_base is not None:
        if not 0 <= selected_base < len(variants):
            raise ValueError(
                f"base_variant_index={selected_base} is outside [0,{len(variants) - 1}]"
            )
        selected = [
            item for item in selected if item.base_variant_index == selected_base
        ]

    if twin_pair is not None:
        if not 0 <= twin_pair.other_variant_index < len(variants):
            raise ValueError(
                f"other_variant_index={twin_pair.other_variant_index} is outside "
                f"[0,{len(variants) - 1}]"
            )
        selected = [
            item
            for item in selected
            if item.base_variant_index == twin_pair.base_variant_index
            and item.other_variant_index == twin_pair.other_variant_index
            and (twin_pair.branch is None or item.branch == twin_pair.branch)
        ]
        if not selected:
            raise ValueError(
                "The requested variant pair/branch has no exact M/M rank-one relation"
            )

    if twin_plane is not None:
        input_normal_product = _product_plane_physical_normal(
            np.asarray(twin_plane.plane_product, dtype=float),
            product_metric,
        )
        angles: list[tuple[float, PTMCTwinRelation]] = []
        for relation in selected:
            base = variants[relation.base_variant_index]
            relation_normal_product = (
                base.polar_rotation_product_from_parent
                @ relation.deformed_twin_plane_normal_base
            )
            angles.append(
                (
                    _projective_angle_deg(
                        input_normal_product,
                        relation_normal_product,
                    ),
                    relation,
                )
            )
        if not angles:
            raise ValueError(
                "No exact M/M twin relations exist for the selected base variant"
            )
        nearest_angle, nearest_relation = min(angles, key=lambda item: item[0])
        selected = [
            relation
            for angle, relation in angles
            if angle <= twin_plane.plane_tolerance_deg
        ]
        if not selected:
            raise ValueError(
                "No exact M/M twin relation matches the supplied product twin plane "
                f"within {twin_plane.plane_tolerance_deg:g} deg. Nearest exact relation "
                f"is base={nearest_relation.base_variant_index}, "
                f"other={nearest_relation.other_variant_index}, "
                f"branch={nearest_relation.branch}, angle={nearest_angle:.6g} deg."
            )

    parameter_roots: list[PTMCParameterRoots] = []
    solutions: list[PTMCHabitSolution] = []
    continuous: list[PTMCContinuousFamily] = []
    for relation in selected:
        base = variants[relation.base_variant_index]
        other = variants[relation.other_variant_index]
        increment = np.outer(relation.a, relation.n_reference)
        roots = solve_affine_ptmc_parameters(
            base.U,
            increment,
            dilatational_factor=dilatational_factor,
            parameter_name="other_variant_volume_fraction",
            domain=(0.0, 1.0),
            polynomial_tolerance=polynomial_tolerance,
            middle_stretch_tolerance=middle_stretch_tolerance,
        )
        parameter_roots.append(roots)
        if roots.continuum:
            continuous.append(
                PTMCContinuousFamily(
                    lis_type=LISType.TWIN.value,
                    base_variant_index=base.index,
                    other_variant_index=other.index,
                    twin_branch=relation.branch,
                    parameter_name=roots.parameter_name,
                    domain=roots.domain,
                    dilatational_factor=float(dilatational_factor),
                    polynomial_coefficients_ascending=(
                        roots.polynomial_coefficients_ascending
                    ),
                    polynomial_verification_residual=(
                        roots.polynomial_verification_residual
                    ),
                    note=(
                        "Every fraction in [0,1] satisfies the determinant condition. "
                        "This continuum is not replaced by a finite arbitrary sample."
                    ),
                )
            )
            continue

        for fraction in roots.discrete_roots:
            F_pre = base.U + float(fraction) * increment
            effective_shear = abs(float(fraction)) * relation.twin_shear_magnitude
            solutions.extend(
                _habit_solution_from_predeformation(
                    lis_type=LISType.TWIN,
                    base_variant=base,
                    other_variant=other,
                    twin_relation=relation,
                    parameter_name=roots.parameter_name,
                    parameter_value=float(fraction),
                    lattice_invariant_shear_magnitude=effective_shear,
                    F_pre=F_pre,
                    lis_plane_normal_pre_habit=(
                        relation.deformed_twin_plane_normal_base
                    ),
                    parent_lattice=parent_lattice,
                    product_lattice=product_lattice,
                    dilatational_factor=dilatational_factor,
                    eigenvalue_tolerance=eigenvalue_tolerance,
                )
            )

    proper_parent = sum(float(np.linalg.det(item)) > 0.0 for item in parent_symmetry)
    proper_product = sum(float(np.linalg.det(item)) > 0.0 for item in product_symmetry)
    return _build_report(
        transformation_id=transformation_id,
        parent_phase_id=parent_phase_id,
        product_phase_id=product_phase_id,
        lis_type=LISType.TWIN,
        dilatational_factor=dilatational_factor,
        variants=variants,
        twin_relations=tuple(selected),
        parameter_roots=parameter_roots,
        solutions=solutions,
        continuous_families=continuous,
        full_parent_symmetry_order=len(parent_symmetry),
        proper_parent_symmetry_order=proper_parent,
        full_product_symmetry_order=len(product_symmetry),
        proper_product_symmetry_order=proper_product,
    )


def analyze_ptmc_slip(
    parent_lattice: Lattice,
    product_lattice: Lattice,
    correspondence: Correspondence | Array,
    parent_symmetry_matrices: Iterable[Array],
    product_symmetry_matrices: Iterable[Array],
    slip_system: PTMCSlipSystemInput,
    *,
    dilatational_factor: float = 1.0,
    transformation_id: str = "manual_ptmc",
    parent_phase_id: str = "parent",
    product_phase_id: str = "product",
    algebraic_tolerance: float = 1.0e-10,
    eigenvalue_tolerance: float = 1.0e-8,
    middle_stretch_tolerance: float = 1.0e-7,
    polynomial_tolerance: float = 1.0e-10,
) -> PTMCReport:
    """Enumerate classical slip-PTMC solutions for the supplied product slip system."""

    parent_metric = parent_lattice.metric()
    product_metric = product_lattice.metric()
    parent_symmetry = _validated_operations(
        parent_symmetry_matrices,
        parent_metric,
        name="parent",
        tolerance=max(algebraic_tolerance, 1.0e-9),
    )
    product_symmetry = _validated_operations(
        product_symmetry_matrices,
        product_metric,
        name="product",
        tolerance=max(algebraic_tolerance, 1.0e-9),
    )
    C = _correspondence_array(correspondence)
    variants = _build_variants(
        parent_metric,
        product_metric,
        C,
        parent_symmetry,
        algebraic_tolerance=algebraic_tolerance,
    )

    if slip_system.base_variant_index is None:
        selected_variants = list(variants)
    else:
        if not 0 <= slip_system.base_variant_index < len(variants):
            raise ValueError(
                f"base_variant_index={slip_system.base_variant_index} is outside "
                f"[0,{len(variants) - 1}]"
            )
        selected_variants = [variants[slip_system.base_variant_index]]

    direction_product = _product_direction_physical(
        np.asarray(slip_system.direction_product, dtype=float),
        product_metric,
    )
    plane_normal_product = _product_plane_physical_normal(
        np.asarray(slip_system.plane_product, dtype=float),
        product_metric,
    )
    if abs(float(direction_product @ plane_normal_product)) > 1.0e-10:
        raise AssertionError("Metric conversion broke slip direction/plane incidence")

    parameter_roots: list[PTMCParameterRoots] = []
    solutions: list[PTMCHabitSolution] = []
    continuous: list[PTMCContinuousFamily] = []
    for base in selected_variants:
        polar = base.polar_rotation_product_from_parent
        shear_direction = _unit(
            polar.T @ direction_product,
            name="slip direction in U frame",
        )
        shear_plane_normal = _unit(
            polar.T @ plane_normal_product,
            name="slip plane normal in U frame",
        )
        if abs(float(shear_direction @ shear_plane_normal)) > 1.0e-10:
            raise AssertionError(
                "PTMC polar-frame conversion broke slip-plane incidence"
            )

        # F_pre = (I + gamma s⊗q) U
        increment = np.outer(shear_direction, shear_plane_normal) @ base.U
        domain = (
            (-float(slip_system.max_abs_shear), float(slip_system.max_abs_shear))
            if slip_system.max_abs_shear is not None
            else None
        )
        roots = solve_affine_ptmc_parameters(
            base.U,
            increment,
            dilatational_factor=dilatational_factor,
            parameter_name="slip_shear_gamma",
            domain=domain,
            polynomial_tolerance=polynomial_tolerance,
            middle_stretch_tolerance=middle_stretch_tolerance,
        )
        parameter_roots.append(roots)
        if roots.continuum:
            continuous.append(
                PTMCContinuousFamily(
                    lis_type=LISType.SLIP.value,
                    base_variant_index=base.index,
                    other_variant_index=None,
                    twin_branch=None,
                    parameter_name=roots.parameter_name,
                    domain=roots.domain,
                    dilatational_factor=float(dilatational_factor),
                    polynomial_coefficients_ascending=(
                        roots.polynomial_coefficients_ascending
                    ),
                    polynomial_verification_residual=(
                        roots.polynomial_verification_residual
                    ),
                    note=(
                        "The determinant condition is identically satisfied over the "
                        "requested slip-shear domain. The family is not sampled as if "
                        "the samples were exhaustive."
                    ),
                )
            )
            continue

        for gamma in roots.discrete_roots:
            F_pre = (
                np.eye(3) + float(gamma) * np.outer(shear_direction, shear_plane_normal)
            ) @ base.U
            solutions.extend(
                _habit_solution_from_predeformation(
                    lis_type=LISType.SLIP,
                    base_variant=base,
                    other_variant=None,
                    twin_relation=None,
                    parameter_name=roots.parameter_name,
                    parameter_value=float(gamma),
                    lattice_invariant_shear_magnitude=abs(float(gamma)),
                    F_pre=F_pre,
                    lis_plane_normal_pre_habit=shear_plane_normal,
                    parent_lattice=parent_lattice,
                    product_lattice=product_lattice,
                    dilatational_factor=dilatational_factor,
                    eigenvalue_tolerance=eigenvalue_tolerance,
                )
            )

    proper_parent = sum(float(np.linalg.det(item)) > 0.0 for item in parent_symmetry)
    proper_product = sum(float(np.linalg.det(item)) > 0.0 for item in product_symmetry)
    return _build_report(
        transformation_id=transformation_id,
        parent_phase_id=parent_phase_id,
        product_phase_id=product_phase_id,
        lis_type=LISType.SLIP,
        dilatational_factor=dilatational_factor,
        variants=variants,
        twin_relations=(),
        parameter_roots=parameter_roots,
        solutions=solutions,
        continuous_families=continuous,
        full_parent_symmetry_order=len(parent_symmetry),
        proper_parent_symmetry_order=proper_parent,
        full_product_symmetry_order=len(product_symmetry),
        proper_product_symmetry_order=proper_product,
    )


@dataclass(frozen=True)
class PTMCCrystalInput:
    """PTCLab-style high-level input with a rigorous PTMC backend."""

    parent_lattice: Lattice
    product_lattice: Lattice
    correspondence: Correspondence | Array
    parent_point_group: str
    product_point_group: str
    transformation_id: str = "manual_ptmc"
    parent_phase_id: str = "parent"
    product_phase_id: str = "product"

    def _symmetry(
        self,
        numerical_policy: NumericalPolicy,
    ) -> tuple[tuple[Array, ...], tuple[Array, ...]]:
        parent = _point_group_operations_for_lattice(
            self.parent_point_group,
            self.parent_lattice,
            tolerance=numerical_policy.representation,
        )
        product = _point_group_operations_for_lattice(
            self.product_point_group,
            self.product_lattice,
            tolerance=numerical_policy.representation,
        )
        return parent, product

    def analyze_all_twinning(
        self,
        *,
        base_variant_index: int | None = None,
        dilatational_factor: float = 1.0,
        numerical_policy: NumericalPolicy = DEFAULT_NUMERICAL_POLICY,
    ) -> PTMCReport:
        parent_symmetry, product_symmetry = self._symmetry(numerical_policy)
        return analyze_ptmc_twinning(
            self.parent_lattice,
            self.product_lattice,
            self.correspondence,
            parent_symmetry,
            product_symmetry,
            base_variant_index=base_variant_index,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent_phase_id,
            product_phase_id=self.product_phase_id,
            algebraic_tolerance=numerical_policy.algebraic,
            eigenvalue_tolerance=numerical_policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * numerical_policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(numerical_policy.algebraic, 1.0e-10),
        )

    def analyze_twin_plane(
        self,
        twin_plane: PTMCTwinPlaneInput,
        *,
        dilatational_factor: float = 1.0,
        numerical_policy: NumericalPolicy = DEFAULT_NUMERICAL_POLICY,
    ) -> PTMCReport:
        parent_symmetry, product_symmetry = self._symmetry(numerical_policy)
        return analyze_ptmc_twinning(
            self.parent_lattice,
            self.product_lattice,
            self.correspondence,
            parent_symmetry,
            product_symmetry,
            twin_plane=twin_plane,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent_phase_id,
            product_phase_id=self.product_phase_id,
            algebraic_tolerance=numerical_policy.algebraic,
            eigenvalue_tolerance=numerical_policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * numerical_policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(numerical_policy.algebraic, 1.0e-10),
        )

    def analyze_twin_pair(
        self,
        twin_pair: PTMCTwinPairInput,
        *,
        dilatational_factor: float = 1.0,
        numerical_policy: NumericalPolicy = DEFAULT_NUMERICAL_POLICY,
    ) -> PTMCReport:
        parent_symmetry, product_symmetry = self._symmetry(numerical_policy)
        return analyze_ptmc_twinning(
            self.parent_lattice,
            self.product_lattice,
            self.correspondence,
            parent_symmetry,
            product_symmetry,
            twin_pair=twin_pair,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent_phase_id,
            product_phase_id=self.product_phase_id,
            algebraic_tolerance=numerical_policy.algebraic,
            eigenvalue_tolerance=numerical_policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * numerical_policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(numerical_policy.algebraic, 1.0e-10),
        )

    def analyze_slip(
        self,
        slip_system: PTMCSlipSystemInput,
        *,
        dilatational_factor: float = 1.0,
        numerical_policy: NumericalPolicy = DEFAULT_NUMERICAL_POLICY,
    ) -> PTMCReport:
        parent_symmetry, product_symmetry = self._symmetry(numerical_policy)
        return analyze_ptmc_slip(
            self.parent_lattice,
            self.product_lattice,
            self.correspondence,
            parent_symmetry,
            product_symmetry,
            slip_system,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent_phase_id,
            product_phase_id=self.product_phase_id,
            algebraic_tolerance=numerical_policy.algebraic,
            eigenvalue_tolerance=numerical_policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * numerical_policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(numerical_policy.algebraic, 1.0e-10),
        )


class PTMCAdapter:
    """Project-bound PTMC adapter for nonstandard symmetry settings and workflows."""

    def __init__(self, project: Any, transformation_id: str) -> None:
        project.validate().assert_passed()
        self.project = project
        self.transformation_id = transformation_id
        self.transformation = project.transformation(transformation_id)
        self.parent = project.phase(self.transformation.parent_phase_id)
        self.product = project.phase(self.transformation.product_phase_id)

    def _operations(self) -> tuple[tuple[Array, ...], tuple[Array, ...]]:
        parent = tuple(self.parent.symmetry_matrices())
        product = tuple(self.product.symmetry_matrices())
        if not parent:
            raise ValueError(
                "PTMC requires explicit parent symmetry operators in ProjectState"
            )
        if not product:
            raise ValueError(
                "PTMC requires explicit product symmetry operators in ProjectState"
            )
        return parent, product

    def analyze_all_twinning(
        self,
        *,
        base_variant_index: int | None = None,
        dilatational_factor: float = 1.0,
    ) -> PTMCReport:
        parent_ops, product_ops = self._operations()
        policy = self.project.numerical_policy
        return analyze_ptmc_twinning(
            self.parent.lattice,
            self.product.lattice,
            self.transformation.correspondence,
            parent_ops,
            product_ops,
            base_variant_index=base_variant_index,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent.phase_id,
            product_phase_id=self.product.phase_id,
            algebraic_tolerance=policy.algebraic,
            eigenvalue_tolerance=policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(policy.algebraic, 1.0e-10),
        )

    def analyze_twin_plane(
        self,
        twin_plane: PTMCTwinPlaneInput,
        *,
        dilatational_factor: float = 1.0,
    ) -> PTMCReport:
        parent_ops, product_ops = self._operations()
        policy = self.project.numerical_policy
        return analyze_ptmc_twinning(
            self.parent.lattice,
            self.product.lattice,
            self.transformation.correspondence,
            parent_ops,
            product_ops,
            twin_plane=twin_plane,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent.phase_id,
            product_phase_id=self.product.phase_id,
            algebraic_tolerance=policy.algebraic,
            eigenvalue_tolerance=policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(policy.algebraic, 1.0e-10),
        )

    def analyze_twin_pair(
        self,
        twin_pair: PTMCTwinPairInput,
        *,
        dilatational_factor: float = 1.0,
    ) -> PTMCReport:
        parent_ops, product_ops = self._operations()
        policy = self.project.numerical_policy
        return analyze_ptmc_twinning(
            self.parent.lattice,
            self.product.lattice,
            self.transformation.correspondence,
            parent_ops,
            product_ops,
            twin_pair=twin_pair,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent.phase_id,
            product_phase_id=self.product.phase_id,
            algebraic_tolerance=policy.algebraic,
            eigenvalue_tolerance=policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(policy.algebraic, 1.0e-10),
        )

    def analyze_slip(
        self,
        slip_system: PTMCSlipSystemInput,
        *,
        dilatational_factor: float = 1.0,
    ) -> PTMCReport:
        parent_ops, product_ops = self._operations()
        policy = self.project.numerical_policy
        return analyze_ptmc_slip(
            self.parent.lattice,
            self.product.lattice,
            self.transformation.correspondence,
            parent_ops,
            product_ops,
            slip_system,
            dilatational_factor=dilatational_factor,
            transformation_id=self.transformation_id,
            parent_phase_id=self.parent.phase_id,
            product_phase_id=self.product.phase_id,
            algebraic_tolerance=policy.algebraic,
            eigenvalue_tolerance=policy.exact_eigenvalue,
            middle_stretch_tolerance=max(
                10.0 * policy.exact_eigenvalue,
                1.0e-7,
            ),
            polynomial_tolerance=max(policy.algebraic, 1.0e-10),
        )
