"""Minimal operator cross-lock examples."""

import numpy as np

from cualni_cryst.operator_crosslock import OperatorCrosslockService, render_report
from cualni_cryst.orientation import OrientationService
from cualni_cryst.project_state import james_hane_6m_reference_project

project = james_hane_6m_reference_project()
orientations = OrientationService(project)
crosslock = OperatorCrosslockService(project)

# 1) Reference correspondence-derived polar candidate.
polar = orientations.polar_orientation("do3_to_6m_reference")
print(render_report(crosslock.build(polar), details=True))

# 2) Any user OR can be bound explicitly to the same correspondence hypothesis.
#    This deliberately does NOT imply that the user OR was generated by C.
generic = orientations.state_from_axis_angle(
    "do3",
    "6m",
    np.array([1.0, 2.0, 3.0]),
    17.0,
    transformation_id="do3_to_6m_reference",
)
print()
print(render_report(crosslock.build(generic)))
